# 1:

# sudo apt-get install postgresql postgresql-plpython-9.3

# done.

# 2.

sudo su - postgres

man pg_upgradecluster

# get rid of existing 9.3 created by install:

pg_dropcluster --stop 9.3 main


# 3. OK go 4 it:

postgres@eracks-ng:~$ pg_upgradecluster 9.1 main
Stopping old cluster...
Disabling connections to the old cluster during upgrade...
Restarting old cluster with restricted connections...
Creating new cluster 9.3/main ...
  config /etc/postgresql/9.3/main
  data   /var/lib/postgresql/9.3/main
  locale en_US.UTF-8
  port   5433
Disabling connections to the new cluster during upgrade...
Roles, databases, schemas, ACLs...
Fixing hardcoded library paths for stored procedures...
Upgrading database eracksdb...
Analyzing database eracksdb...
Fixing hardcoded library paths for stored procedures...
Upgrading database postgres...
Analyzing database postgres...
Fixing hardcoded library paths for stored procedures...
Upgrading database template1...
Analyzing database template1...
Re-enabling connections to the old cluster...
Re-enabling connections to the new cluster...
Copying old configuration files...
Copying old start.conf...
Copying old pg_ctl.conf...
Copying old server.crt...
Copying old server.key...
Stopping target cluster...
Stopping old cluster...
Disabling automatic startup of old cluster...
Configuring old cluster to use a different port (5433)...
Starting target cluster on the original port...
Success. Please check that the upgraded cluster works. If it does,
you can remove the old cluster with

  pg_dropcluster 9.1 main
postgres@eracks-ng:~$ 


4.  Now test & remove:

apt-get -s remove postgresql-9.1 postgresql-client-9.1 postgresql-plpython-9.1

DONE.
