calist=[('', 'Select CA County'),
 ("(8.75,'Alameda')", 'Alameda 8.75%'),
 ("(9.0,'Alameda.SanLeandro')", 'Alameda (San Leandro) 9%'),
 ("(9.25,'Alameda.UnionCity')", 'Alameda (Union City) 9.25%'),
 ("(7.25,'Alpine')", 'Alpine 7.25%'),
 ("(7.75,'Amador')", 'Amador 7.75%'),
 ("(7.25,'Butte')", 'Butte 7.25%'),
 ("(7.25,'Calaveras')", 'Calaveras 7.25%'),
 ("(7.25,'Colusa')", 'Colusa 7.25%'),
 ("(7.75,'Colusa.Williams')", 'Colusa (Williams) 7.75%'),
 ("(8.25,'Contra Costa')", 'Contra Costa 8.25%'),
 ("(8.75,'Contra Costa.Concord_Pinole_Richmond')",
  'Contra Costa (Concord, Pinole, Richmond) 8.75%'),
 ("(9.25,'Contra Costa.ElCerrito')", 'Contra Costa (El Cerrito) 9.25%'),
 ("(7.25,'Del Norte')", 'Del Norte 7.25%'),
 ("(7.25,'El Dorado')", 'El Dorado 7.25%'),
 ("(7.75,'El Dorado.Placerville_SouthLakeTahoe')",
  'El Dorado (Placerville, South Lake Tahoe) 7.75%'),
 ("(7.975,'Fresno')", 'Fresno 7.975%'),
 ("(8.475,'Fresno.Reedley_Selma')", 'Fresno (Reedley, Selma) 8.475%'),
 ("(8.725,'Fresno.Sanger')", 'Fresno (Sanger) 8.725%'),
 ("(7.25,'Glenn')", 'Glenn 7.25%'),
 ("(7.25,'Humboldt')", 'Humboldt 7.25%'),
 ("(8.0,'Humboldt.Arcata_Eureka_Trinidad')",
  'Humboldt (Arcata, Eureka, Trinidad) 8%'),
 ("(7.75,'Imperial')", 'Imperial 7.75%'),
 ("(8.25,'Imperial.Calexico')", 'Imperial (Calexico) 8.25%'),
 ("(7.75,'Inyo')", 'Inyo 7.75%'),
 ("(7.25,'Kern')", 'Kern 7.25%'),
 ("(8.25,'Kern.Arvin_Delano')", 'Kern (Arvin, Delano) 8.25%'),
 ("(7.25,'Kings')", 'Kings 7.25%'),
 ("(7.25,'Lake')", 'Lake 7.25%'),
 ("(7.75,'Lake.ClearlakeHighlands_ClearlakePark_Clearlake_Lakeport')",
  'Lake (Clearlake Highlands, Clearlake Park, Clearlake, Lakeport) 7.75%'),
 ("(7.25,'Lassen')", 'Lassen 7.25%'),
 ("(8.75,'Los Angeles')", 'Los Angeles 8.75%'),
 ("(9.25,'Los Angeles.Avalon_ElMonte_Inglewood_SantaMonica_SouthElMonte')",
  'Los Angeles (Avalon, El Monte, Inglewood, Santa Monica, South El Monte) 9.25%'),
 ("(9.75,'Los Angeles.PicoRivera_SouthGate')",
  'Los Angeles (Pico Rivera, South Gate) 9.75%'),
 ("(7.75,'Madera')", 'Madera 7.75%'),
 ("(8.0,'Marin')", 'Marin 8%'),
 ("(8.5,'Marin.Fairfax_HamiltonA.F.B._Ignacio_Novato_SanRafael')",
  'Marin (Fairfax, Hamilton A.F.B., Ignacio, Novato, San Rafael) 8.5%'),
 ("(7.75,'Mariposa')", 'Mariposa 7.75%'),
 ("(7.375,'Mendocino')", 'Mendocino 7.375%'),
 ("(7.875,'Mendocino.FortBragg_PointArena_Ukiah_Willits')",
  'Mendocino (Fort Bragg, Point Arena, Ukiah, Willits) 7.875%'),
 ("(7.25,'Merced')", 'Merced 7.25%'),
 ("(7.75,'Merced.Gustine_LosBanos_Merced')",
  'Merced (Gustine, Los Banos, Merced) 7.75%'),
 ("(7.25,'Modoc')", 'Modoc 7.25%'),
 ("(7.25,'Mono')", 'Mono 7.25%'),
 ("(7.75,'Mono.MammothLakes')", 'Mono (Mammoth Lakes) 7.75%'),
 ("(7.25,'Monterey')", 'Monterey 7.25%'),
 ("(8.25,'Monterey.DelReyOaks_Marina_PacificGrove_Seaside')",
  'Monterey (Del Rey Oaks, Marina, Pacific Grove, Seaside) 8.25%'),
 ("(7.75,'Monterey.Salinas_SandCity')", 'Monterey (Salinas, Sand City) 7.75%'),
 ("(7.75,'Napa')", 'Napa 7.75%'),
 ("(7.375,'Nevada')", 'Nevada 7.375%'),
 ("(7.875,'Nevada.NevadaCity_Truckee')",
  'Nevada (Nevada City, Truckee) 7.875%'),
 ("(7.75,'Orange')", 'Orange 7.75%'),
 ("(8.25,'Orange.LaHabra')", 'Orange (La Habra) 8.25%'),
 ("(7.25,'Placer')", 'Placer 7.25%'),
 ("(7.25,'Plumas')", 'Plumas 7.25%'),
 ("(7.75,'Riverside')", 'Riverside 7.75%'),
 ("(8.75,'Riverside.CathedralCity_PalmSprings_SmokeTree')",
  'Riverside (Cathedral City, Palm Springs, Smoke Tree) 8.75%'),
 ("(7.75,'Sacramento')", 'Sacramento 7.75%'),
 ("(8.25,'Sacramento.Galt')", 'Sacramento (Galt) 8.25%'),
 ("(7.25,'San Benito')", 'San Benito 7.25%'),
 ("(8.25,'San Benito.Hollister')", 'San Benito (Hollister) 8.25%'),
 ("(8.0,'San Benito.SanJuanBautista')", 'San Benito (San Juan Bautista) 8%'),
 ("(7.75,'San Bernardino')", 'San Bernardino 7.75%'),
 ("(8.0,'San Bernardino.Montclair_NortonA.F.B._SanBernardino')",
  'San Bernardino (Montclair, Norton A.F.B., San Bernardino) 8%'),
 ("(7.75,'San Diego')", 'San Diego 7.75%'),
 ("(8.75,'San Diego.ElCajon_NationalCity')",
  'San Diego (El Cajon, National City) 8.75%'),
 ("(8.5,'San Diego.LaMesa')", 'San Diego (La Mesa) 8.5%'),
 ("(8.25,'San Diego.Vista')", 'San Diego (Vista) 8.25%'),
 ("(8.5,'San Francisco')", 'San Francisco 8.5%'),
 ("(7.75,'San Joaquin')", 'San Joaquin 7.75%'),
 ("(8.25,'San Joaquin.Manteca_Tracy')", 'San Joaquin (Manteca, Tracy) 8.25%'),
 ("(8.0,'San Joaquin.Stockton')", 'San Joaquin (Stockton) 8%'),
 ("(7.25,'San Luis Obispo')", 'San Luis Obispo 7.25%'),
 ("(7.75,'San Luis Obispo.ArroyoGrande_DelMarHeights_GroverBeach_MorroBay_PismoBeach_SanLuisObispo_ShellBeach')",
  'San Luis Obispo (Arroyo Grande, Del Mar Heights, Grover Beach, Morro Bay, Pismo Beach, San Luis Obispo, Shell Beach) 7.75%'),
 ("(8.25,'San Mateo')", 'San Mateo 8.25%'),
 ("(8.5,'San Mateo.Hillsdale_SanMateo')",
  'San Mateo (Hillsdale, San Mateo) 8.5%'),
 ("(7.75,'Santa Barbara')", 'Santa Barbara 7.75%'),
 ("(8.25,'Santa Clara')", 'Santa Clara 8.25%'),
 ("(8.5,'Santa Clara.Campbell')", 'Santa Clara (Campbell) 8.5%'),
 ("(8.0,'Santa Cruz')", 'Santa Cruz 8%'),
 ("(8.25,'Santa Cruz.Capitola_Watsonville')",
  'Santa Cruz (Capitola, Watsonville) 8.25%'),
 ("(8.5,'Santa Cruz.SantaCruz_Seabright')",
  'Santa Cruz (Santa Cruz, Seabright) 8.5%'),
 ("(7.25,'Shasta')", 'Shasta 7.25%'),
 ("(7.25,'Sierra')", 'Sierra 7.25%'),
 ("(7.25,'Siskiyou')", 'Siskiyou 7.25%'),
 ("(7.5,'Siskiyou.MountShasta')", 'Siskiyou (Mount Shasta) 7.5%'),
 ("(7.375,'Solano')", 'Solano 7.375%'),
 ("(8.375,'Solano.MareIsland_Vallejo')",
  'Solano (Mare Island, Vallejo) 8.375%'),
 ("(8.0,'Sonoma')", 'Sonoma 8%'),
 ("(8.5,'Sonoma.Cotati_RohnertPark_SantaRosa')",
  'Sonoma (Cotati, Rohnert Park, Santa Rosa) 8.5%'),
 ("(8.25,'Sonoma.Sebastopol')", 'Sonoma (Sebastopol) 8.25%'),
 ("(7.375,'Stanislaus')", 'Stanislaus 7.375%'),
 ("(7.875,'Stanislaus.Ceres_Oakdale')", 'Stanislaus (Ceres, Oakdale) 7.875%'),
 ("(7.25,'Sutter')", 'Sutter 7.25%'),
 ("(7.25,'Tehama')", 'Tehama 7.25%'),
 ("(7.25,'Trinity')", 'Trinity 7.25%'),
 ("(7.75,'Tulare')", 'Tulare 7.75%'),
 ("(8.5,'Tulare.Dinuba')", 'Tulare (Dinuba) 8.5%'),
 ("(8.25,'Tulare.Farmersville_Porterville_Tulare')",
  'Tulare (Farmersville, Porterville, Tulare) 8.25%'),
 ("(8.0,'Tulare.Visalia')", 'Tulare (Visalia) 8%'),
 ("(7.25,'Tuolumne')", 'Tuolumne 7.25%'),
 ("(7.75,'Tuolumne.Sonora')", 'Tuolumne (Sonora) 7.75%'),
 ("(7.25,'Ventura')", 'Ventura 7.25%'),
 ("(7.75,'Ventura.Naval_Oxnard_PortHueneme')",
  'Ventura (Naval, Oxnard, Port Hueneme) 7.75%'),
 ("(7.25,'Yolo')", 'Yolo 7.25%'),
 ("(7.75,'Yolo.Broderick_Bryte_Davis_WestSacramento')",
  'Yolo (Broderick, Bryte, Davis, West Sacramento) 7.75%'),
 ("(8.0,'Yolo.Woodland')", 'Yolo (Woodland) 8%'),
 ("(7.25,'Yuba')", 'Yuba 7.25%'),
 ("(7.75,'Yuba.Wheatland')", 'Yuba (Wheatland) 7.75%')]